spring.application.name=operation-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/smartdm
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=dms