spring.application.name=operation-service

server.port=8083

# ---- Database (same smartdm / dms as auth-service) ----
spring.datasource.url=jdbc:postgresql://localhost:5432/smartdm
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=dms

# ---- JWT (MUST be the SAME secret as auth-service) ----
app.jwt.secret=wSdQhWVugazOO4AQQl0G6O2jn5Py4/IWCQz6l88I1gfAkR+4seORHULV5j7cbzdJ

# ---- CORS (same as auth-service, for your Flutter web app) ----
app.cors.allowed-origins=http://localhost:*,http://127.0.0.1:*